let g:coc_global_extensions = [
\ 'coc-git',
\ 'coc-json',
\ 'coc-lists',
\ 'coc-go',
\ 'coc-java',
\ 'coc-python',
\ 'coc-sh',
\ 'coc-tsserver',
\ 'coc-eslint',
\ 'coc-prettier',
\ 'coc-yaml',
\ 'coc-markdownlint',
\ 'coc-spell-checker',
\ 'coc-css',
\ 'coc-rust-analyzer',
\ 'coc-pairs',
\ ]
