terminal:
  searchOptions: {}
  colorScheme:
    name: Atom-custom
    foreground: '#c5c8c6'
    background: '#161719'
    cursor: '#0095e1'
    colors:
      - '#000000'
      - '#fd5ff1'
      - '#87c38a'
      - '#ffd7b1'
      - '#85befd'
      - '#b9b6fc'
      - '#85befd'
      - '#e0e0e0'
      - '#6b6b6b'
      - '#fd5ff1'
      - '#94fa36'
      - '#f5ffa8'
      - '#96cbfe'
      - '#b9b6fc'
      - '#85befd'
      - '#e0e0e0'
  environment: {}
  profile: zsh
  font: JetBrainsMono Nerd Font
  cursorBlink: false
  bell: 'off'
  fallbackFont: UDEV Gothic NF
  fontSize: 16
  alwaysUseWorkingDirectory: false
  background: theme
  customColorSchemes:
    - name: Atom-custom
      foreground: '#c5c8c6'
      background: '#161719'
      cursor: '#0095e1'
      colors:
        - '#000000'
        - '#fd5ff1'
        - '#87c38a'
        - '#ffd7b1'
        - '#85befd'
        - '#b9b6fc'
        - '#85befd'
        - '#e0e0e0'
        - '#6b6b6b'
        - '#fd5ff1'
        - '#94fa36'
        - '#f5ffa8'
        - '#96cbfe'
        - '#b9b6fc'
        - '#85befd'
        - '#e0e0e0'
  ligatures: false
  frontend: xterm-webgl
hotkeys:
  shell: {}
  profile: {}
  new-tab:
    - - ⌘-Shift-T
    - - Alt-Shift-T
  move-tab-left:
    - - ⌘-Shift-Left
    - - Alt-Shift-Left
  move-tab-right:
    - - ⌘-Shift-Right
    - - Alt-Shift-Right
  close-tab:
    - - ⌘-Shift-C
    - - Alt-Shift-C
  next-tab:
    - - ⌘-Shift-L
    - - Alt-Shift-L
  previous-tab:
    - - ⌘-Shift-H
    - - Alt-Shift-H
  split-right:
    - - Ctrl-⌘-S
    - - Ctrl-Alt-S
  split-bottom:
    - - ⌘-Shift-S
    - - Alt-Shift-S
  pane-nav-left:
    - - Ctrl-⌘-H
    - - Ctrl-Alt-H
  pane-nav-right:
    - - Ctrl-⌘-L
    - - Ctrl-Alt-L
  pane-nav-down:
    - - Ctrl-⌘-J
    - - Ctrl-Alt-J
  pane-nav-up:
    - - Ctrl-⌘-K
    - - Ctrl-Alt-K
  close-pane:
    - - Ctrl-⌘-C
    - - Ctrl-Alt-C
  reopen-tab:
    - - ⌘-Shift-B
    - - Alt-Shift-B
  toggle-last-tab:
    - - ⌘-Shift-R
    - - Alt-Shift-R
  rename-tab: []
  copy:
    - - ⌘-Shift-Y
    - - Alt-Shift-Y
  paste:
    - - ⌘-Shift-P
    - - Alt-Shift-P
  zoom-in:
    - - ⌘-Shift-;
    - - Alt-Shift-;
  zoom-out:
    - - ⌘-Shift--
    - - Alt-Shift--
  reset-zoom:
    - - ⌘-Shift-0
    - - Alt-Shift-0
  search:
    - - ⌘-Shift-F
    - - Alt-Shift-F
  pane-focus-all:
    - - Ctrl-⌘-I
    - - Ctrl-Alt-I
serial: {}
ssh: {}
appearance:
  theme: Standard
  opacity: 1
  frame: thin
  vibrancy: false
enableAnalytics: false
pluginBlacklist: []
enableWelcomeTab: false
clickableLinks: {}
version: 3
profiles: []
configSync:
  parts: {}
profileDefaults: {}
hacks: {}
docker: {}
saveOutput: {}
